--基础流水表ddl
create table bi_ysfdb.yuanchengwithlabel (
inbankcard string comment '转入卡'
, tsdate int comment '交易日期yyyymmdd'
, tsyyyymm int comment '交易月份 年月'
, tsmon int comment '交易月份 [1,12]'
, tsday int comment '交易日期 [1,31]'
, tshour int comment '交易时间小时 [0,23]'
, tsdayofweek int comment '星期 [0,6]'
, timestamp_s bigint comment '交易unix 时间戳，单位为秒'
, transamt double comment '交易金额'
, outbankcard string comment '转出卡'
, inbankcardattr string comment '转入卡性质'
, usrid string comment '转出用户id'
, usrgender string comment '转出用户性别'
, usrage int comment '转出用户年龄'
, usrregdate int comment '注册日期yyyymmdd'
, prikey string comment '交易唯一识别号'
, tsdaydiff_d20201201 int comment '历史交易相对时间，天'
, tsdaydiff_d20201202 int comment '历史交易相对时间，天'
, tsdaydiff_d20201203 int comment '历史交易相对时间，天'
, tsdaydiff_d20201204 int comment '历史交易相对时间，天'
, tsdaydiff_d20201205 int comment '历史交易相对时间，天'
, tsdaydiff_d20201206 int comment '历史交易相对时间，天'
, tsdaydiff_d20201207 int comment '历史交易相对时间，天'
, tsdaydiff_d20201208 int comment '历史交易相对时间，天'
, tsdaydiff_d20201209 int comment '历史交易相对时间，天'
, tsdaydiff_d20201210 int comment '历史交易相对时间，天'
, tsdaydiff_d20201211 int comment '历史交易相对时间，天'
, tsdaydiff_d20201212 int comment '历史交易相对时间，天'
, tsdaydiff_d20201213 int comment '历史交易相对时间，天'
, tsdaydiff_d20201214 int comment '历史交易相对时间，天'
, tsdaydiff_d20201215 int comment '历史交易相对时间，天'
, tsdaydiff_d20201216 int comment '历史交易相对时间，天'
, tsdaydiff_d20201217 int comment '历史交易相对时间，天'
, tsdaydiff_d20201218 int comment '历史交易相对时间，天'
, tsdaydiff_d20201219 int comment '历史交易相对时间，天'
, tsdaydiff_d20201220 int comment '历史交易相对时间，天'
, tsdaydiff_d20201221 int comment '历史交易相对时间，天'
, tsdaydiff_d20201222 int comment '历史交易相对时间，天'
, tsdaydiff_d20201223 int comment '历史交易相对时间，天'
, tsdaydiff_d20201224 int comment '历史交易相对时间，天'
, tsdaydiff_d20201225 int comment '历史交易相对时间，天'
, tsdaydiff_d20201226 int comment '历史交易相对时间，天'
, tsdaydiff_d20201227 int comment '历史交易相对时间，天'
, tsdaydiff_d20201228 int comment '历史交易相对时间，天'
, tsdaydiff_d20201229 int comment '历史交易相对时间，天'
, tsdaydiff_d20201230 int comment '历史交易相对时间，天'
, tsdaydiff_d20201231 int comment '历史交易相对时间，天'
)
comment '远程转账交易自相交表'
row format delimited fields terminated by ','
stored as textfile
location
'hdfs://master:9000/user/hive/warehouse/mydatabase.db/yuanchengwithlabel'
;



--基本特征select语句
select
prikey
,sum              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__SUM__TRANSAMT__DAY1_30                                                       --TRANSAMT|SUM|$|最近30天
,avg              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__AVG__TRANSAMT__DAY1_30                                                       --TRANSAMT|AVG|$|最近30天
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__COUNT__TRANSAMT__DAY1_30                                                     --TRANSAMT|COUNT|$|最近30天
,min              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__MIN__TRANSAMT__DAY1_30                                                       --TRANSAMT|MIN|$|最近30天
,max              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__MAX__TRANSAMT__DAY1_30                                                       --TRANSAMT|MAX|$|最近30天
,std              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__STD__TRANSAMT__DAY1_30                                                       --TRANSAMT|STD|$|最近30天
,sum              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then TRANSAMT else null end                                                                                                                 )  as SET0__SUM__TRANSAMT__DAY1_7                                                        --TRANSAMT|SUM|$|最近7天
,avg              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then TRANSAMT else null end                                                                                                                 )  as SET0__AVG__TRANSAMT__DAY1_7                                                        --TRANSAMT|AVG|$|最近7天
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then TRANSAMT else null end                                                                                                                 )  as SET0__COUNT__TRANSAMT__DAY1_7                                                      --TRANSAMT|COUNT|$|最近7天
,min              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then TRANSAMT else null end                                                                                                                 )  as SET0__MIN__TRANSAMT__DAY1_7                                                        --TRANSAMT|MIN|$|最近7天
,max              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then TRANSAMT else null end                                                                                                                 )  as SET0__MAX__TRANSAMT__DAY1_7                                                        --TRANSAMT|MAX|$|最近7天
,std              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then TRANSAMT else null end                                                                                                                 )  as SET0__STD__TRANSAMT__DAY1_7                                                        --TRANSAMT|STD|$|最近7天
,sum              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then TRANSAMT else null end                                                                                                                 )  as SET0__SUM__TRANSAMT__DAY1_3                                                        --TRANSAMT|SUM|$|最近3天
,avg              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then TRANSAMT else null end                                                                                                                 )  as SET0__AVG__TRANSAMT__DAY1_3                                                        --TRANSAMT|AVG|$|最近3天
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then TRANSAMT else null end                                                                                                                 )  as SET0__COUNT__TRANSAMT__DAY1_3                                                      --TRANSAMT|COUNT|$|最近3天
,min              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then TRANSAMT else null end                                                                                                                 )  as SET0__MIN__TRANSAMT__DAY1_3                                                        --TRANSAMT|MIN|$|最近3天
,max              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then TRANSAMT else null end                                                                                                                 )  as SET0__MAX__TRANSAMT__DAY1_3                                                        --TRANSAMT|MAX|$|最近3天
,std              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then TRANSAMT else null end                                                                                                                 )  as SET0__STD__TRANSAMT__DAY1_3                                                        --TRANSAMT|STD|$|最近3天
,sum              (  case when (TSDAYDIFF_d20201201=1) then TRANSAMT else null end                                                                                                                                             )  as SET0__SUM__TRANSAMT__DAY1                                                          --TRANSAMT|SUM|$|最近1天
,avg              (  case when (TSDAYDIFF_d20201201=1) then TRANSAMT else null end                                                                                                                                             )  as SET0__AVG__TRANSAMT__DAY1                                                          --TRANSAMT|AVG|$|最近1天
,count            (  case when (TSDAYDIFF_d20201201=1) then TRANSAMT else null end                                                                                                                                             )  as SET0__COUNT__TRANSAMT__DAY1                                                        --TRANSAMT|COUNT|$|最近1天
,min              (  case when (TSDAYDIFF_d20201201=1) then TRANSAMT else null end                                                                                                                                             )  as SET0__MIN__TRANSAMT__DAY1                                                          --TRANSAMT|MIN|$|最近1天
,max              (  case when (TSDAYDIFF_d20201201=1) then TRANSAMT else null end                                                                                                                                             )  as SET0__MAX__TRANSAMT__DAY1                                                          --TRANSAMT|MAX|$|最近1天
,std              (  case when (TSDAYDIFF_d20201201=1) then TRANSAMT else null end                                                                                                                                             )  as SET0__STD__TRANSAMT__DAY1                                                          --TRANSAMT|STD|$|最近1天
,sum              (  case when (TSDAYDIFF_d20201201=2) then TRANSAMT else null end                                                                                                                                             )  as SET0__SUM__TRANSAMT__DAY2                                                          --TRANSAMT|SUM|$|最近第2天
,avg              (  case when (TSDAYDIFF_d20201201=2) then TRANSAMT else null end                                                                                                                                             )  as SET0__AVG__TRANSAMT__DAY2                                                          --TRANSAMT|AVG|$|最近第2天
,count            (  case when (TSDAYDIFF_d20201201=2) then TRANSAMT else null end                                                                                                                                             )  as SET0__COUNT__TRANSAMT__DAY2                                                        --TRANSAMT|COUNT|$|最近第2天
,min              (  case when (TSDAYDIFF_d20201201=2) then TRANSAMT else null end                                                                                                                                             )  as SET0__MIN__TRANSAMT__DAY2                                                          --TRANSAMT|MIN|$|最近第2天
,max              (  case when (TSDAYDIFF_d20201201=2) then TRANSAMT else null end                                                                                                                                             )  as SET0__MAX__TRANSAMT__DAY2                                                          --TRANSAMT|MAX|$|最近第2天
,std              (  case when (TSDAYDIFF_d20201201=2) then TRANSAMT else null end                                                                                                                                             )  as SET0__STD__TRANSAMT__DAY2                                                          --TRANSAMT|STD|$|最近第2天
,sum              (  case when (TSDAYDIFF_d20201201=3) then TRANSAMT else null end                                                                                                                                             )  as SET0__SUM__TRANSAMT__DAY3                                                          --TRANSAMT|SUM|$|最近第3天
,avg              (  case when (TSDAYDIFF_d20201201=3) then TRANSAMT else null end                                                                                                                                             )  as SET0__AVG__TRANSAMT__DAY3                                                          --TRANSAMT|AVG|$|最近第3天
,count            (  case when (TSDAYDIFF_d20201201=3) then TRANSAMT else null end                                                                                                                                             )  as SET0__COUNT__TRANSAMT__DAY3                                                        --TRANSAMT|COUNT|$|最近第3天
,min              (  case when (TSDAYDIFF_d20201201=3) then TRANSAMT else null end                                                                                                                                             )  as SET0__MIN__TRANSAMT__DAY3                                                          --TRANSAMT|MIN|$|最近第3天
,max              (  case when (TSDAYDIFF_d20201201=3) then TRANSAMT else null end                                                                                                                                             )  as SET0__MAX__TRANSAMT__DAY3                                                          --TRANSAMT|MAX|$|最近第3天
,std              (  case when (TSDAYDIFF_d20201201=3) then TRANSAMT else null end                                                                                                                                             )  as SET0__STD__TRANSAMT__DAY3                                                          --TRANSAMT|STD|$|最近第3天
,sum              (  case when (TSDAYDIFF_d20201201=4) then TRANSAMT else null end                                                                                                                                             )  as SET0__SUM__TRANSAMT__DAY4                                                          --TRANSAMT|SUM|$|最近第4天
,avg              (  case when (TSDAYDIFF_d20201201=4) then TRANSAMT else null end                                                                                                                                             )  as SET0__AVG__TRANSAMT__DAY4                                                          --TRANSAMT|AVG|$|最近第4天
,count            (  case when (TSDAYDIFF_d20201201=4) then TRANSAMT else null end                                                                                                                                             )  as SET0__COUNT__TRANSAMT__DAY4                                                        --TRANSAMT|COUNT|$|最近第4天
,min              (  case when (TSDAYDIFF_d20201201=4) then TRANSAMT else null end                                                                                                                                             )  as SET0__MIN__TRANSAMT__DAY4                                                          --TRANSAMT|MIN|$|最近第4天
,max              (  case when (TSDAYDIFF_d20201201=4) then TRANSAMT else null end                                                                                                                                             )  as SET0__MAX__TRANSAMT__DAY4                                                          --TRANSAMT|MAX|$|最近第4天
,std              (  case when (TSDAYDIFF_d20201201=4) then TRANSAMT else null end                                                                                                                                             )  as SET0__STD__TRANSAMT__DAY4                                                          --TRANSAMT|STD|$|最近第4天
,sum              (  case when (TSDAYDIFF_d20201201=5) then TRANSAMT else null end                                                                                                                                             )  as SET0__SUM__TRANSAMT__DAY5                                                          --TRANSAMT|SUM|$|最近第5天
,avg              (  case when (TSDAYDIFF_d20201201=5) then TRANSAMT else null end                                                                                                                                             )  as SET0__AVG__TRANSAMT__DAY5                                                          --TRANSAMT|AVG|$|最近第5天
,count            (  case when (TSDAYDIFF_d20201201=5) then TRANSAMT else null end                                                                                                                                             )  as SET0__COUNT__TRANSAMT__DAY5                                                        --TRANSAMT|COUNT|$|最近第5天
,min              (  case when (TSDAYDIFF_d20201201=5) then TRANSAMT else null end                                                                                                                                             )  as SET0__MIN__TRANSAMT__DAY5                                                          --TRANSAMT|MIN|$|最近第5天
,max              (  case when (TSDAYDIFF_d20201201=5) then TRANSAMT else null end                                                                                                                                             )  as SET0__MAX__TRANSAMT__DAY5                                                          --TRANSAMT|MAX|$|最近第5天
,std              (  case when (TSDAYDIFF_d20201201=5) then TRANSAMT else null end                                                                                                                                             )  as SET0__STD__TRANSAMT__DAY5                                                          --TRANSAMT|STD|$|最近第5天
,sum              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=10) then TRANSAMT else null end                                                                                                                )  as SET0__SUM__TRANSAMT__DAY1_10                                                       --TRANSAMT|SUM|$|最近10天
,avg              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=10) then TRANSAMT else null end                                                                                                                )  as SET0__AVG__TRANSAMT__DAY1_10                                                       --TRANSAMT|AVG|$|最近10天
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=10) then TRANSAMT else null end                                                                                                                )  as SET0__COUNT__TRANSAMT__DAY1_10                                                     --TRANSAMT|COUNT|$|最近10天
,min              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=10) then TRANSAMT else null end                                                                                                                )  as SET0__MIN__TRANSAMT__DAY1_10                                                       --TRANSAMT|MIN|$|最近10天
,max              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=10) then TRANSAMT else null end                                                                                                                )  as SET0__MAX__TRANSAMT__DAY1_10                                                       --TRANSAMT|MAX|$|最近10天
,std              (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=10) then TRANSAMT else null end                                                                                                                )  as SET0__STD__TRANSAMT__DAY1_10                                                       --TRANSAMT|STD|$|最近10天
,sum              (  case when (TSDAYDIFF_d20201201>10 AND TSDAYDIFF_d20201201<=20) then TRANSAMT else null end                                                                                                                )  as SET0__SUM__TRANSAMT__DAY10_20                                                      --TRANSAMT|SUM|$|最近10_20天
,avg              (  case when (TSDAYDIFF_d20201201>10 AND TSDAYDIFF_d20201201<=20) then TRANSAMT else null end                                                                                                                )  as SET0__AVG__TRANSAMT__DAY10_20                                                      --TRANSAMT|AVG|$|最近10_20天
,count            (  case when (TSDAYDIFF_d20201201>10 AND TSDAYDIFF_d20201201<=20) then TRANSAMT else null end                                                                                                                )  as SET0__COUNT__TRANSAMT__DAY10_20                                                    --TRANSAMT|COUNT|$|最近10_20天
,min              (  case when (TSDAYDIFF_d20201201>10 AND TSDAYDIFF_d20201201<=20) then TRANSAMT else null end                                                                                                                )  as SET0__MIN__TRANSAMT__DAY10_20                                                      --TRANSAMT|MIN|$|最近10_20天
,max              (  case when (TSDAYDIFF_d20201201>10 AND TSDAYDIFF_d20201201<=20) then TRANSAMT else null end                                                                                                                )  as SET0__MAX__TRANSAMT__DAY10_20                                                      --TRANSAMT|MAX|$|最近10_20天
,std              (  case when (TSDAYDIFF_d20201201>10 AND TSDAYDIFF_d20201201<=20) then TRANSAMT else null end                                                                                                                )  as SET0__STD__TRANSAMT__DAY10_20                                                      --TRANSAMT|STD|$|最近10_20天
,sum              (  case when (TSDAYDIFF_d20201201>20 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__SUM__TRANSAMT__DAY20_30                                                      --TRANSAMT|SUM|$|最近10_20天
,avg              (  case when (TSDAYDIFF_d20201201>20 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__AVG__TRANSAMT__DAY20_30                                                      --TRANSAMT|AVG|$|最近10_20天
,count            (  case when (TSDAYDIFF_d20201201>20 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__COUNT__TRANSAMT__DAY20_30                                                    --TRANSAMT|COUNT|$|最近10_20天
,min              (  case when (TSDAYDIFF_d20201201>20 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__MIN__TRANSAMT__DAY20_30                                                      --TRANSAMT|MIN|$|最近10_20天
,max              (  case when (TSDAYDIFF_d20201201>20 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__MAX__TRANSAMT__DAY20_30                                                      --TRANSAMT|MAX|$|最近10_20天
,std              (  case when (TSDAYDIFF_d20201201>20 AND TSDAYDIFF_d20201201<=30) then TRANSAMT else null end                                                                                                                )  as SET0__STD__TRANSAMT__DAY20_30                                                      --TRANSAMT|STD|$|最近10_20天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then TSDATE else null end                                                                                                                  )) as SET1__CNTDIST__TSDATE__DAY1_30                                                     --TSDATE|CNTDIST|$|最近30天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then TSDATE else null end                                                                                                                   )) as SET1__CNTDIST__TSDATE__DAY1_7                                                      --TSDATE|CNTDIST|$|最近7天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then TSDATE else null end                                                                                                                   )) as SET1__CNTDIST__TSDATE__DAY1_3                                                      --TSDATE|CNTDIST|$|最近3天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) then TSDATE else null end                                                                                                                   )) as SET1__CNTDIST__TSDATE__DAY1                                                        --TSDATE|CNTDIST|$|最近1天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then OUTBANKCARD else null end                                                                                                             )) as SET1__CNTDIST__OUTBANKCARD__DAY1_30                                                --OUTBANKCARD|CNTDIST|$|最近30天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then OUTBANKCARD else null end                                                                                                              )) as SET1__CNTDIST__OUTBANKCARD__DAY1_7                                                 --OUTBANKCARD|CNTDIST|$|最近7天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then OUTBANKCARD else null end                                                                                                              )) as SET1__CNTDIST__OUTBANKCARD__DAY1_3                                                 --OUTBANKCARD|CNTDIST|$|最近3天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) then OUTBANKCARD else null end                                                                                                              )) as SET1__CNTDIST__OUTBANKCARD__DAY1                                                   --OUTBANKCARD|CNTDIST|$|最近1天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then USRID else null end                                                                                                                   )) as SET1__CNTDIST__USRID__DAY1_30                                                      --USRID|CNTDIST|$|最近30天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then USRID else null end                                                                                                                    )) as SET1__CNTDIST__USRID__DAY1_7                                                       --USRID|CNTDIST|$|最近7天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then USRID else null end                                                                                                                    )) as SET1__CNTDIST__USRID__DAY1_3                                                       --USRID|CNTDIST|$|最近3天
,count(distinct   (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) then USRID else null end                                                                                                                    )) as SET1__CNTDIST__USRID__DAY1                                                         --USRID|CNTDIST|$|最近1天
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) and (TRANSAMT>0 AND TRANSAMT<=100000) then TRANSAMT else null end                                                                          )  as SET2__COUNT__TRANSAMT__DAY1_30__HISTRANSAMT_0_1000                                 --TRANSAMT|COUNT|$|最近30天|交易金额0_1000
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) and (TRANSAMT>0 AND TRANSAMT<=100000) then TRANSAMT else null end                                                                           )  as SET2__COUNT__TRANSAMT__DAY1_7__HISTRANSAMT_0_1000                                  --TRANSAMT|COUNT|$|最近7天|交易金额0_1000
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) and (TRANSAMT>0 AND TRANSAMT<=100000) then TRANSAMT else null end                                                                           )  as SET2__COUNT__TRANSAMT__DAY1_3__HISTRANSAMT_0_1000                                  --TRANSAMT|COUNT|$|最近3天|交易金额0_1000
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) and (TRANSAMT>0 AND TRANSAMT<=100000) then TRANSAMT else null end                                                                           )  as SET2__COUNT__TRANSAMT__DAY1__HISTRANSAMT_0_1000                                    --TRANSAMT|COUNT|$|最近1天|交易金额0_1000
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) and (USRAGE>=20 AND USRAGE<30) then USRAGE else null end                                                                                   )  as SET3__COUNT__USRAGE__DAY1_30__HISUSRAGE_20_30                                      --USRAGE|COUNT|$|最近30天|20_30岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) and (USRAGE>=30 AND USRAGE<40) then USRAGE else null end                                                                                   )  as SET3__COUNT__USRAGE__DAY1_30__HISUSRAGE_30_40                                      --USRAGE|COUNT|$|最近30天|30_40岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) and (USRAGE>=40 AND USRAGE<50) then USRAGE else null end                                                                                   )  as SET3__COUNT__USRAGE__DAY1_30__HISUSRAGE_40_50                                      --USRAGE|COUNT|$|最近30天|40_50岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) and (USRAGE>=50 AND USRAGE<60) then USRAGE else null end                                                                                   )  as SET3__COUNT__USRAGE__DAY1_30__HISUSRAGE_50_60                                      --USRAGE|COUNT|$|最近30天|50_60岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) and (USRAGE>=60) then USRAGE else null end                                                                                                 )  as SET3__COUNT__USRAGE__DAY1_30__HISUSRAGE_GT60                                       --USRAGE|COUNT|$|最近30天|60岁以上
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) and (USRAGE>=20 AND USRAGE<30) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1_7__HISUSRAGE_20_30                                       --USRAGE|COUNT|$|最近7天|20_30岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) and (USRAGE>=30 AND USRAGE<40) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1_7__HISUSRAGE_30_40                                       --USRAGE|COUNT|$|最近7天|30_40岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) and (USRAGE>=40 AND USRAGE<50) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1_7__HISUSRAGE_40_50                                       --USRAGE|COUNT|$|最近7天|40_50岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) and (USRAGE>=50 AND USRAGE<60) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1_7__HISUSRAGE_50_60                                       --USRAGE|COUNT|$|最近7天|50_60岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) and (USRAGE>=60) then USRAGE else null end                                                                                                  )  as SET3__COUNT__USRAGE__DAY1_7__HISUSRAGE_GT60                                        --USRAGE|COUNT|$|最近7天|60岁以上
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) and (USRAGE>=20 AND USRAGE<30) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1_3__HISUSRAGE_20_30                                       --USRAGE|COUNT|$|最近3天|20_30岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) and (USRAGE>=30 AND USRAGE<40) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1_3__HISUSRAGE_30_40                                       --USRAGE|COUNT|$|最近3天|30_40岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) and (USRAGE>=40 AND USRAGE<50) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1_3__HISUSRAGE_40_50                                       --USRAGE|COUNT|$|最近3天|40_50岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) and (USRAGE>=50 AND USRAGE<60) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1_3__HISUSRAGE_50_60                                       --USRAGE|COUNT|$|最近3天|50_60岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) and (USRAGE>=60) then USRAGE else null end                                                                                                  )  as SET3__COUNT__USRAGE__DAY1_3__HISUSRAGE_GT60                                        --USRAGE|COUNT|$|最近3天|60岁以上
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) and (USRAGE>=20 AND USRAGE<30) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1__HISUSRAGE_20_30                                         --USRAGE|COUNT|$|最近1天|20_30岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) and (USRAGE>=30 AND USRAGE<40) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1__HISUSRAGE_30_40                                         --USRAGE|COUNT|$|最近1天|30_40岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) and (USRAGE>=40 AND USRAGE<50) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1__HISUSRAGE_40_50                                         --USRAGE|COUNT|$|最近1天|40_50岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) and (USRAGE>=50 AND USRAGE<60) then USRAGE else null end                                                                                    )  as SET3__COUNT__USRAGE__DAY1__HISUSRAGE_50_60                                         --USRAGE|COUNT|$|最近1天|50_60岁
,count            (  case when (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) and (USRAGE>=60) then USRAGE else null end                                                                                                  )  as SET3__COUNT__USRAGE__DAY1__HISUSRAGE_GT60                                          --USRAGE|COUNT|$|最近1天|60岁以上
,count            (  case when (USRGENDER='F') and (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then USRGENDER else null end                                                                                           )  as SET4__COUNT__USRGENDER__GENDER_F__DAY1_30                                          --USRGENDER|COUNT|$|女|最近30天
,count            (  case when (USRGENDER='F') and (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then USRGENDER else null end                                                                                            )  as SET4__COUNT__USRGENDER__GENDER_F__DAY1_7                                           --USRGENDER|COUNT|$|女|最近7天
,count            (  case when (USRGENDER='F') and (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then USRGENDER else null end                                                                                            )  as SET4__COUNT__USRGENDER__GENDER_F__DAY1_3                                           --USRGENDER|COUNT|$|女|最近3天
,count            (  case when (USRGENDER='F') and (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) then USRGENDER else null end                                                                                            )  as SET4__COUNT__USRGENDER__GENDER_F__DAY1                                             --USRGENDER|COUNT|$|女|最近1天
,count            (  case when (USRGENDER='M') and (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=30) then USRGENDER else null end                                                                                           )  as SET4__COUNT__USRGENDER__GENDER_M__DAY1_30                                          --USRGENDER|COUNT|$|男|最近30天
,count            (  case when (USRGENDER='M') and (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=7) then USRGENDER else null end                                                                                            )  as SET4__COUNT__USRGENDER__GENDER_M__DAY1_7                                           --USRGENDER|COUNT|$|男|最近7天
,count            (  case when (USRGENDER='M') and (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=3) then USRGENDER else null end                                                                                            )  as SET4__COUNT__USRGENDER__GENDER_M__DAY1_3                                           --USRGENDER|COUNT|$|男|最近3天
,count            (  case when (USRGENDER='M') and (TSDAYDIFF_d20201201>=1 AND TSDAYDIFF_d20201201<=1) then USRGENDER else null end                                                                                            )  as SET4__COUNT__USRGENDER__GENDER_M__DAY1                                             --USRGENDER|COUNT|$|男|最近1天
from bi_ysfdb.yuanchengwithlabel
group by prikey
;



